import {
    accountNode,
    arrayTypeNode,
    booleanTypeNode,
    booleanValueNode,
    bytesTypeNode,
    bytesValueNode,
    constantDiscriminatorNode,
    constantValueNode,
    definedTypeLinkNode,
    definedTypeNode,
    enumEmptyVariantTypeNode,
    enumStructVariantTypeNode,
    enumTypeNode,
    enumValueNode,
    fieldDiscriminatorNode,
    fixedSizeTypeNode,
    instructionAccountNode,
    instructionArgumentNode,
    instructionNode,
    numberTypeNode,
    numberValueNode,
    programNode,
    remainderCountNode,
    rootNode,
    sizePrefixTypeNode,
    stringTypeNode,
    structFieldTypeNode,
    structFieldValueNode,
    structTypeNode,
    structValueNode,
} from '@codama/nodes';
import { renderMapContains } from '@codama/renderers-core';
import { visit } from '@codama/visitors-core';
import { describe, expect, it } from 'vitest';

import { getRenderMapVisitor } from '../src';

const PROGRAM_ID = '11111111111111111111111111111111';

function renderProgram(program: Partial<Parameters<typeof programNode>[0]>) {
    return visit(rootNode(programNode({ name: 'test', publicKey: PROGRAM_ID, ...program })), getRenderMapVisitor());
}

function expectContains(renderMap: ReturnType<typeof renderProgram>, path: string, ...values: (RegExp | string)[]) {
    values.forEach(value => expect(renderMapContains(renderMap, path, value), String(value)).toBe(true));
}

function expectNotContains(renderMap: ReturnType<typeof renderProgram>, path: string, ...values: (RegExp | string)[]) {
    values.forEach(value => expect(renderMapContains(renderMap, path, value), String(value)).toBe(false));
}

const account = (name: string, isOptional = false) =>
    instructionAccountNode({ isOptional, isSigner: false, isWritable: false, name });

const anchorInstruction = (name: string, discriminator: string) =>
    instructionNode({
        accounts: [account('authority')],
        arguments: [
            instructionArgumentNode({
                defaultValue: bytesValueNode('base16', discriminator),
                defaultValueStrategy: 'omitted',
                name: 'discriminator',
                type: fixedSizeTypeNode(bytesTypeNode(), 8),
            }),
            instructionArgumentNode({ name: 'amount', type: numberTypeNode('u64') }),
        ],
        discriminators: [fieldDiscriminatorNode('discriminator', 0)],
        name,
    });

describe('generated file header', () => {
    it('starts with the canonical Go generated-code marker', () => {
        const renderMap = renderProgram({ instructions: [anchorInstruction('route', 'e517cb977ae3ad2a')] });
        expectContains(renderMap, 'instructions.go', /^\/\/ Code generated by @codama\/renderers-go\. DO NOT EDIT\.$/m);
        expectContains(renderMap, 'instruction_route.go', /^\/\/ Code generated by .* DO NOT EDIT\.$/m);
    });
});

describe('enums', () => {
    it('renders empty variants of data enums as EmptyVariant fields with index constants', () => {
        const renderMap = renderProgram({
            definedTypes: [
                definedTypeNode({
                    name: 'swap',
                    type: enumTypeNode([
                        enumEmptyVariantTypeNode('saber'),
                        enumStructVariantTypeNode(
                            'crema',
                            structTypeNode([structFieldTypeNode({ name: 'aToB', type: booleanTypeNode() })]),
                        ),
                        enumEmptyVariantTypeNode('lifinity'),
                    ]),
                }),
            ],
        });
        expectContains(
            renderMap,
            'type_swap.go',
            'Enum ag_binary.BorshEnum `borsh_enum:"true"`',
            'Saber ag_binary.EmptyVariant',
            /Crema struct \{\s*AToB bool\s*\}/,
            'Lifinity ag_binary.EmptyVariant',
            'Swap_Saber ag_binary.BorshEnum = iota',
            /Swap_Crema\n/,
            /Swap_Lifinity\n/,
        );
    });

    it('sizes scalar enums by their IDL discriminant', () => {
        const renderMap = renderProgram({
            definedTypes: [
                definedTypeNode({
                    name: 'nonceState',
                    type: enumTypeNode(
                        [enumEmptyVariantTypeNode('uninitialized'), enumEmptyVariantTypeNode('initialized')],
                        {
                            size: numberTypeNode('u32'),
                        },
                    ),
                }),
            ],
        });
        expectContains(
            renderMap,
            'type_nonce_state.go',
            'type NonceState uint32',
            'NonceState_Uninitialized NonceState = iota',
        );
    });

    it('renders data-enum default values as composite literals', () => {
        const swap = definedTypeNode({
            name: 'swap',
            type: enumTypeNode([
                enumEmptyVariantTypeNode('saber'),
                enumStructVariantTypeNode(
                    'crema',
                    structTypeNode([structFieldTypeNode({ name: 'aToB', type: booleanTypeNode() })]),
                ),
            ]),
        });
        const side = definedTypeNode({
            name: 'side',
            type: enumTypeNode([enumEmptyVariantTypeNode('bid'), enumEmptyVariantTypeNode('ask')]),
        });
        const arg = (name: string, type: string, value: ReturnType<typeof enumValueNode>) =>
            instructionArgumentNode({
                defaultValue: value,
                defaultValueStrategy: 'omitted',
                name,
                type: definedTypeLinkNode(type),
            });
        const renderMap = renderProgram({
            definedTypes: [swap, side],
            instructions: [
                instructionNode({
                    arguments: [
                        arg('empty', 'swap', enumValueNode('swap', 'saber')),
                        arg(
                            'data',
                            'swap',
                            enumValueNode(
                                'swap',
                                'crema',
                                structValueNode([structFieldValueNode('aToB', booleanValueNode(true))]),
                            ),
                        ),
                        arg('scalar', 'side', enumValueNode('side', 'ask')),
                    ],
                    name: 'route',
                }),
            ],
        });
        expectContains(
            renderMap,
            'instruction_route.go',
            'encoder.Encode(Swap(Swap{Enum: Swap_Saber}))',
            'encoder.Encode(Swap(func() (v Swap) { v.Enum = Swap_Crema; v.Crema.AToB = true; return v }()))',
            'encoder.Encode(Side(Side_Ask))',
        );
    });

    it('keeps scalar enums as typed iota constants', () => {
        const renderMap = renderProgram({
            definedTypes: [
                definedTypeNode({
                    name: 'side',
                    type: enumTypeNode([enumEmptyVariantTypeNode('bid'), enumEmptyVariantTypeNode('ask')]),
                }),
            ],
        });
        expectContains(renderMap, 'type_side.go', 'type Side uint8', 'Side_Bid Side = iota', /Side_Ask\n/);
        expectNotContains(renderMap, 'type_side.go', 'BorshEnum', 'EmptyVariant');
    });
});

describe('instruction discriminators', () => {
    it('writes, validates and dispatches on the explicit IDL bytes', () => {
        const renderMap = renderProgram({
            instructions: [
                anchorInstruction('route', 'e517cb977ae3ad2a'),
                anchorInstruction('claim', '3ec6d6c1d59f6cd2'),
            ],
        });
        expectContains(
            renderMap,
            'instruction_route.go',
            'var RouteDiscriminator = []byte{229, 23, 203, 151, 122, 227, 173, 42}',
            'func (inst *Route) Build() *Instruction',
            'func (inst *Route) ValidateAndBuild() (*Instruction, error)',
            'TypeID: ag_binary.TypeIDFromBytes(RouteDiscriminator)',
            'encoder.WriteBytes(RouteDiscriminator, false)',
            'errors.New("accounts.Authority is not set")',
            '// RouteDiscriminator is the discriminator that prefixes the serialized data.',
            'if got, err := decoder.ReadNBytes(len(RouteDiscriminator)); err != nil {',
            'if !bytes.Equal(got, RouteDiscriminator)',
        );
        expectNotContains(renderMap, 'instruction_route.go', 'func (inst Route) Build()', 'var tmp [8]uint8');
        expectContains(
            renderMap,
            'instructions.go',
            'case hasDiscriminator(decoder, 0, ClaimDiscriminator):',
            'impl = new(Claim)',
            'case hasDiscriminator(decoder, 0, RouteDiscriminator):',
            'typeID = ag_binary.TypeIDFromBytes(RouteDiscriminator)',
            'inst.Impl.(ag_binary.BinaryMarshaler)',
            /func init\(\) \{\s*_ = ag_solanago\.RegisterInstructionDecoder\(ProgramID, registryDecodeInstruction\)/,
        );
        expectNotContains(
            renderMap,
            'instructions.go',
            'InstructionImplDef',
            'WriteUint8(inst.TypeID',
            'NewVariantDefinition',
        );
    });

    it('renders numeric discriminators as little-endian bytes', () => {
        const renderMap = renderProgram({
            instructions: [
                instructionNode({
                    arguments: [
                        instructionArgumentNode({
                            defaultValue: numberValueNode(2),
                            defaultValueStrategy: 'omitted',
                            name: 'discriminator',
                            type: numberTypeNode('u32'),
                        }),
                    ],
                    discriminators: [fieldDiscriminatorNode('discriminator', 0)],
                    name: 'transferSol',
                }),
            ],
        });
        expectContains(renderMap, 'instruction_transfer_sol.go', 'var TransferSolDiscriminator = []byte{2, 0, 0, 0}');
    });

    it('writes constant discriminators before the arguments and dispatches on them', () => {
        const renderMap = renderProgram({
            instructions: [
                instructionNode({
                    arguments: [instructionArgumentNode({ name: 'amount', type: numberTypeNode('u64') })],
                    discriminators: [
                        constantDiscriminatorNode(constantValueNode(numberTypeNode('u8'), numberValueNode(8))),
                    ],
                    name: 'tagged',
                }),
                instructionNode({
                    arguments: [
                        instructionArgumentNode({ name: 'version', type: numberTypeNode('u8') }),
                        instructionArgumentNode({
                            defaultValue: numberValueNode(9),
                            defaultValueStrategy: 'omitted',
                            name: 'discriminator',
                            type: numberTypeNode('u8'),
                        }),
                    ],
                    discriminators: [fieldDiscriminatorNode('discriminator', 1)],
                    name: 'versioned',
                }),
            ],
        });
        expectContains(
            renderMap,
            'instruction_tagged.go',
            'var TaggedDiscriminator = []byte{8}',
            /MarshalWithEncoder\(encoder \*ag_binary\.Encoder\) error \{\s*if err := encoder\.WriteBytes\(TaggedDiscriminator, false\)/,
            /UnmarshalWithDecoder\(decoder \*ag_binary\.Decoder\) error \{\s*if got, err := decoder\.ReadNBytes\(len\(TaggedDiscriminator\)\)/,
            'TypeID: ag_binary.TypeIDFromBytes(TaggedDiscriminator)',
        );
        expectContains(
            renderMap,
            'instruction_versioned.go',
            'var VersionedDiscriminator = []byte{9}',
            /encoder\.Encode\(inst\.Version\)[\s\S]*encoder\.WriteBytes\(VersionedDiscriminator, false\)/,
        );
        expectContains(
            renderMap,
            'instructions.go',
            'case hasDiscriminator(decoder, 1, VersionedDiscriminator):',
            'case hasDiscriminator(decoder, 0, TaggedDiscriminator):',
        );
    });

    it('decodes a single undiscriminated instruction directly', () => {
        const renderMap = renderProgram({
            instructions: [
                instructionNode({
                    arguments: [instructionArgumentNode({ name: 'amount', type: numberTypeNode('u64') })],
                    name: 'addMemo',
                }),
            ],
        });
        expectContains(renderMap, 'instructions.go', 'impl := new(AddMemo)', 'typeID := ag_binary.NoTypeIDDefaultID');
        expectNotContains(renderMap, 'instructions.go', 'case hasDiscriminator');
        expectContains(renderMap, 'instruction_add_memo.go', 'TypeID: ag_binary.NoTypeIDDefaultID');
    });
});

describe('account discriminators', () => {
    it('writes the constant and validates it before decoding the field', () => {
        const renderMap = renderProgram({
            accounts: [
                accountNode({
                    data: structTypeNode([
                        structFieldTypeNode({
                            defaultValue: bytesValueNode('base16', '17b7f83760d8ac60'),
                            defaultValueStrategy: 'omitted',
                            name: 'discriminator',
                            type: fixedSizeTypeNode(bytesTypeNode(), 8),
                        }),
                        structFieldTypeNode({ name: 'amount', type: numberTypeNode('u64') }),
                    ]),
                    discriminators: [fieldDiscriminatorNode('discriminator', 0)],
                    name: 'bondingCurve',
                }),
            ],
        });
        expectContains(
            renderMap,
            'account_bonding_curve.go',
            'var BondingCurveDiscriminator = []byte{23, 183, 248, 55, 96, 216, 172, 96}',
            'encoder.WriteBytes(BondingCurveDiscriminator, false)',
            'if got, err := decoder.Peek(len(BondingCurveDiscriminator)); err != nil {',
            'if !bytes.Equal(got, BondingCurveDiscriminator)',
            'if err := decoder.Decode(&obj.Discriminator); err != nil {',
        );
        expectNotContains(renderMap, 'account_bonding_curve.go', 'encoder.Encode(obj.Discriminator)');
    });
});

describe('remainder-encoded fields', () => {
    it('writes strings, bytes and arrays without a length prefix and reads the rest of the buffer', () => {
        const renderMap = renderProgram({
            accounts: [
                accountNode({
                    data: structTypeNode([
                        structFieldTypeNode({ name: 'version', type: numberTypeNode('u8') }),
                        structFieldTypeNode({ name: 'payload', type: bytesTypeNode() }),
                    ]),
                    name: 'blob',
                }),
            ],
            instructions: [
                instructionNode({
                    arguments: [instructionArgumentNode({ name: 'memo', type: stringTypeNode('utf8') })],
                    name: 'addMemo',
                }),
                instructionNode({
                    arguments: [
                        instructionArgumentNode({
                            name: 'amounts',
                            type: arrayTypeNode(numberTypeNode('u64'), remainderCountNode()),
                        }),
                        instructionArgumentNode({
                            name: 'prefixed',
                            type: sizePrefixTypeNode(stringTypeNode('utf8'), numberTypeNode('u32')),
                        }),
                    ],
                    name: 'batch',
                }),
            ],
        });
        expectContains(
            renderMap,
            'instruction_add_memo.go',
            'encoder.WriteBytes([]byte(inst.Memo), false)',
            'data, err := decoder.ReadNBytes(decoder.Remaining())',
            'inst.Memo = string(data)',
        );
        expectContains(
            renderMap,
            'instruction_batch.go',
            /for _, item := range inst\.Amounts \{\s*if err := encoder\.Encode\(item\); err != nil/,
            /for decoder\.Remaining\(\) > 0 \{\s*var item uint64/,
            'encoder.Encode(inst.Prefixed)',
        );
        expectContains(renderMap, 'account_blob.go', 'encoder.WriteBytes(obj.Payload, false)', 'obj.Payload = data');
    });
});

describe('optional accounts', () => {
    it('passes unset optional accounts as the program id by default', () => {
        const renderMap = renderProgram({
            instructions: [
                instructionNode({
                    accounts: [account('source'), account('fee', true), account('authority'), account('extra', true)],
                    name: 'route',
                }),
            ],
        });
        expectContains(
            renderMap,
            'instruction_route.go',
            /case 1, 3:\s*meta = ag_solanago\.Meta\(ProgramID\)/,
            'expected at least 3, got %d',
            'padded := make(ag_solanago.AccountMetaSlice, 4)',
        );
        expectNotContains(renderMap, 'instruction_route.go', 'accounts[:4]');
    });

    it('drops unset optional accounts for the omitted strategy', () => {
        const renderMap = renderProgram({
            instructions: [
                instructionNode({
                    accounts: [account('source'), account('fee', true)],
                    name: 'route',
                    optionalAccountStrategy: 'omitted',
                }),
            ],
        });
        expectContains(
            renderMap,
            'instruction_route.go',
            /if meta == nil && i == 1 \{\s*continue/,
            'expected at least 1, got %d',
        );
        expectNotContains(renderMap, 'instruction_route.go', 'Meta(ProgramID)');
    });

    it('copies the account list when there are no optional accounts', () => {
        const renderMap = renderProgram({
            instructions: [instructionNode({ accounts: [account('source')], name: 'route' })],
        });
        expectContains(renderMap, 'instruction_route.go', 'copy(out, inst.AccountMetaSlice)');
        expectNotContains(renderMap, 'instruction_route.go', 'padded :=');
    });
});
